Update BOT.yml

diff --git a/.github/workflows/BOT.yml b/.github/workflows/BOT.yml
--- a/.github/workflows/BOT.yml
+++ b/.github/workflows/BOT.yml
@@ -42,42 +42,27 @@ jobs:
           # Define the directory to check
           DIR_TO_CHECK=".github/workflows"
           
-          # Go to the GitHub workspace
-          cd $GITHUB_WORKSPACE
-
-          # Compute hashes for all files in the directory on PR branch, sort by file path
+          # Compute hashes for PR and base branches directly to files
           echo "Computing PR hashes..."
-          PR_HASHES=$(find "$DIR_TO_CHECK" -type f -exec sha256sum {} + | sort -k 2)
-          echo "PR hashes computed."
+          find "$DIR_TO_CHECK" -type f -exec sha256sum {} + | sort -k 2 > pr_hashes.txt
+          echo "PR hashes computed and written to pr_hashes.txt"
 
-          # Change to the base directory and compute hashes there
-          echo "Changing to base directory..."
-          cd base
           echo "Computing base hashes..."
-          BASE_HASHES=$(find "$DIR_TO_CHECK" -type f -exec sha256sum {} + | sort -k 2)
-          echo "Base hashes computed."
+          find "base/$DIR_TO_CHECK" -type f -exec sha256sum {} + | sort -k 2 > base_hashes.txt
+          echo "Base hashes computed and written to base_hashes.txt"
 
-          # Return to initial directory
-          cd ..
-
-          # Output hashes for diagnostics
-          echo "PR hashes:"
-          echo "$PR_HASHES"
-          echo "Base hashes:"
-          echo "$BASE_HASHES"
-
-          # Save output of diff to a variable to simplify error handling
+          # Compare hashes using diff
           echo "Comparing hashes..."
-          DIFF_OUTPUT=$(diff <(echo "$PR_HASHES") <(echo "$BASE_HASHES"))
-          DIFF_EXIT_CODE=$?
-
-          if [ "$DIFF_EXIT_CODE" -ne 0 ]; then
+          if ! diff pr_hashes.txt base_hashes.txt > hash_diff.txt; then
             echo "Changes detected in $DIR_TO_CHECK."
             echo "Differences detected:"
-            echo "$DIFF_OUTPUT"
+            cat hash_diff.txt
             exit 1
           else
             echo "No changes detected in $DIR_TO_CHECK."
+          # Clean up hash files
+          rm pr_hashes.txt base_hashes.txt hash_diff.txt
+
       - name: Auto approve
         uses: hmarr/auto-approve-action@v2
         with:
